# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bacf5cecbee798f52d165317bf8020e27912d50980c24ffab10e7835607cdf6dda39723ef56ee0f3b604d3ce8c7ddc3fc33eae0c0dcfa930e6c8f6dc9225d392

test:
  secret_key_base: c9ed015042edd244a00f2ce858c7c35436e827dc2bc5c070bb9f84c0b9d6de3f8ff5b4e8f3f57292a78ce01bc5e172813171cf7653213b8c31343b2d04eb1b50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
